name: Testing Engine!

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  generate-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
            use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::tidyverse
            any::rvest

      - name: Run Script
        env:
            RATINGS: ${{ secrets.RATINGS }}
        run: Rscript R/script.R

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
