name: Vinyl Collection
on: [workflow_dispatch]

# on:
#   schedule:
#     - cron: "0 3 * * *"

jobs:
  generate-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
            use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::tidyverse
            any::rvest
            any::jsonlite
            any::lubridate
            any::httr
            any::magrittr
            any::numform

      - name: Vinyl Collection
        env:
          RECORDS: ${{ secrets.RECORDS }}
        run: Rscript R/vinyl.R

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
